# Docker-compose stack for development purposes
# DO NOT USE THIS IN PRODUCTION

name: clic-website-devcontainer

services:
  # Directus service
  directus:
    image: directus/directus
    user: ${UID}:${GID}
    container_name: clic-directus
    environment:
      SECRET: secret
      KEY: key
      DB_CLIENT: postgres
      DB_HOST: directus-postgres
      DB_PORT: 5432
      DB_DATABASE: directus_data
      DB_USER: directus_user
      DB_PASSWORD: directus_pw
      PUBLIC_URL: http://localhost/directus
      ROOT_REDIRECT: /directus/admin
      ADMIN_EMAIL: clic@epfl.ch
      ADMIN_PASSWORD: 1234
    depends_on:
      - directus-postgres
    volumes:
      - ./directus:/share
      - ./directus/uploads:/directus/uploads
      - directus-extensions:/directus-extensions

  # Database for directus
  directus-postgres:
    container_name: clic-postgres
    image: postgres
    environment:
      POSTGRES_DB: directus_data
      POSTGRES_USER: directus_user
      POSTGRES_PASSWORD: directus_pw
    volumes:
      - "directus-data:/var/lib/postgresql/data"

  app:
    # Build the app service from its folder
    build:
      # Build context, relative to the current file
      context: ./app
      # Path to Dockerfile, relative to context
      dockerfile: Dockerfile.dev
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    environment:
      NODE_ENV: development
    volumes:
      # Bind-mount the app project folder into the container
      - type: bind
        source: ./app
        target: /app

  caddy:
    image: caddy
    volumes:
      - "./caddy/Caddyfile.dev:/etc/caddy/Caddyfile"
    ports:
      - "80:80"

volumes:
  # Persist directus database
  directus-data:
  directus-extensions:
