version: "3"

services:
  strapi:
    build:
      context: ../strapi/.devcontainer
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi-postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_data
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_pw
      MEILI_PROTOCOL: http
      MEILI_HOST: meilisearch
      MEILI_MASTER_KEY: meili_master_key
      MEILI_PORT: 7700
    volumes:
      - "..:/app"
    ports:
      - "1337:1337"
    depends_on:
      - strapi-postgres

  strapi-postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi_data
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_pw
    volumes:
      - "strapi-data:/var/lib/postgresql/data"

  meilisearch:
    image: getmeili/meilisearch
    command: ./meilisearch
    environment:
      MEILI_MASTER_KEY: meili_master_key
    volumes:
      - "meilisearch-data:/data.ms"
    ports:
      - "7700:7700"

volumes:
  strapi-data:
  meilisearch-data: